Make action show an API error
buildkite/trigger-pipeline-action pull request #26
Opened 2021-10-08 15:58 UTC by EnricoMi

The action currently silently fails when the API returns an HTTP error code. There is no information on the reason.

This prints the error message provided by the API before failing the action.

2022-05-02 06:02 UTC, ohookins commented
Would love to see this merged.

2023-01-11 00:32 UTC, lizrabuya approved these changes

2023-01-17 23:00 UTC, lizrabuya commented
Hi @EnricoMi I agree this change is beneficial to the users. So we're not blocking it. However, the test suite needs to be updated to reflect this change.

2023-01-18 03:25 UTC, jradtilbrook submitted a review, later dismissed
A small one but might be better. I'm not sure if `<<<` is supported everywhere/is a standard bash syntax 👆

2023-01-18 03:25 UTC, jradtilbrook commented on entrypoint.sh
> +  jq .message <<< "$RESPONSE"
I think we keep this consistent with the rest of the file and switch it to:
```suggestion
if [[ $(echo "$RESPONSE" | jq .id) == null ]]; then
  echo -n "Buildkite API call failed: "
  echo "$RESPONSE" | jq --raw-output ".message"
```

2023-01-20 09:48 UTC, EnricoMi commented
@lizrabuya I agree, this change should be reflected in the tests, but I cannot get them running locally.

The `.github/` directory looks outdated (workflows are now defined in a `workflows` subdirectory in YAML workflow files. Running `act` fails due to this:

    Error: stat /home/enrico/Work/git/trigger-pipeline-action/.github/workflows: no such file or directory

Running `bats tests/` fails with

    bats: /load.bash does not exist

The same when running the tests through `docker://buildkite/plugin-tester`.

If you could provide me with the required commands to execute the tests locally, I'd be glad to add tests.

2023-02-06 09:17 UTC, EnricoMi commented
@lizrabuya @jradtilbrook any hints on how to run the tests locally?

2023-02-09 11:51 UTC, EnricoMi commented
@lizrabuya @jradtilbrook done, bash testing is awesome!

2023-02-10 07:38 UTC, EnricoMi commented
@jeremy what do you think?

2023-02-15 02:42 UTC, lizrabuya requested changes

2023-02-15 02:42 UTC, lizrabuya commented on entrypoint.sh
> +  MESSAGE=$(jq .message <<< "$RESPONSE" 2> /dev/null || true)
@EnricoMi, can we put back @jradtilbrook's feedback in using "<<<" ?

2023-02-15 06:39 UTC, EnricoMi commented
Sure, it's back.

2023-02-17 05:23 UTC, lizrabuya approved these changes

2023-02-17 05:24 UTC, merged