Support additional properties
buildkite/trigger-pipeline-action pull request #33
Opened 2023-02-02 10:01 UTC by fredr

Adds support for linking with pull request via pull request number, and for adding meta_data to the build

2023-03-15 11:35 UTC, fredr commented
Any chance this could get a review? maybe @lizrabuya  or @EnricoMi?
Sorry for pinging directly, but I'm not sure how to progress with this.

2023-03-28 06:13 UTC, lizrabuya requested changes
Suggested for additional test case

2023-03-28 06:13 UTC, lizrabuya commented on tests/entrypoint.bats
LGTM, but can you update the tests with valid meta-data parameters 

`e.g. @test "Creates a build with meta-data vars`

2023-03-29 08:30 UTC, fredr commented on tests/entrypoint.bats
For sure, done! Sorry for not adding that directly. I also added a test for the pull request id

2023-03-30 06:06 UTC, lizrabuya approved these changes
Looks great!

2023-03-30 06:06 UTC, merged